%Visualize output of POEM
%Forecast at one location
%95 years
%Plots of all locations together
%Plots of constant and phenology together
%ppt coloring
%Recruitment variability

clear all
close all

% dpath = '/Users/cpetrik/Dropbox/Princeton/POEM_2.0/CODE/Data/CSV/No_PD_coupling_no_activ_TrefPD/';
% fpath = '/Users/cpetrik/Dropbox/Princeton/POEM_2.0/CODE/Figs/PNG/No_PD_coupling_no_activ_TrefPD/';
dpath = '/Users/cpetrik/Dropbox/Princeton/POEM_2.0/CODE/Data/CSV/No_PD_coupling_no_activ_TrefOrig/';
fpath = '/Users/cpetrik/Dropbox/Princeton/POEM_2.0/CODE/Figs/PNG/No_PD_coupling_no_activ_TrefOrig/';

sname = 'Oneloc_fore_';

load([dpath 'onelocs_fore_recruitment_PV.mat']);
load([dpath 'onelocs_hist_recruitment_PV.mat']);

load('cmap_ppt_angles.mat')

spots = {'GB','EBS','OSP','HOT','BATS','NS'};


%% Each on same axes

for s=1:length(spots)
    loc = spots{s};
    
    %2021-2050
    f9 = figure(9);
    subplot(2,3,s)
    plot(0.9,F1(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(1.9,P1(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(2.9,D1(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1.1,F1(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2.1,P1(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3.1,D1(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 4])
    ylim([0 1])
    set(gca,'XTick',1:3,'XTickLabel',{'F','P','D'})
    title(loc)
    ylabel('2021-2050 Recruitment variability (PV)')
    
    %2071-2100
    f10 = figure(10);
    subplot(2,3,s)
    plot(0.9,F2(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(1.9,P2(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(2.9,D2(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1.1,F2(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2.1,P2(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3.1,D2(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 4])
    ylim([0 1])
    set(gca,'XTick',1:3,'XTickLabel',{'F','P','D'})
    title(loc)
    ylabel('2071-2100 Recruitment variability (PV)')
    
    % Constant
    f11 = figure(11);
    subplot(2,3,s)
    plot(0.9,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(1.9,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(2.9,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1.1,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2.1,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3.1,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 4])
    ylim([0 1])
    set(gca,'XTick',1:3,'XTickLabel',{'F','P','D'})
    title(loc)
    ylabel('Con Recruitment variability (PV)')
    
    % Seasonal
    f12 = figure(12);
    subplot(2,3,s)
    plot(0.9,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(1.9,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(2.9,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1,F1(2*s),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2,P1(2*s),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3,D1(2*s),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(1.1,F2(2*s),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(2.1,P2(2*s),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(3.1,D2(2*s),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 4])
    ylim([0 0.4])
    set(gca,'XTick',1:3,'XTickLabel',{'F','P','D'})
    title(loc)
    ylabel('Con Recruitment variability (PV)')
    
end

%%
print(f9,'-dpng',[fpath sname 'All_oneloc_fore2021-2050_rec_PV.png'])
print(f10,'-dpng',[fpath sname 'All_oneloc_fore2071-2100_rec_PV.png'])
print(f11,'-dpng',[fpath sname 'All_oneloc_fore_const_rec_PV.png'])
print(f12,'-dpng',[fpath sname 'All_oneloc_fore_seas_rec_PV.png'])


%%
for s=1:length(spots)
    figure(1)
    subplot(1,3,1)
    plot(s-0.2,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F1(2*s),'ok',...
        'MarkerFaceColor','m',...
        'MarkerSize',15); hold on;
    plot(s+0.2,F2(2*s),'dk',...
        'MarkerFaceColor','r',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    
    subplot(1,3,2)
    plot(s-0.2,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,P1(2*s),'ok',...
        'MarkerFaceColor','c',...
        'MarkerSize',15); hold on;
    plot(s+0.1,P2(2*s),'dk',...
        'MarkerFaceColor','b',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    
    subplot(1,3,3)
    plot(s-0.2,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D1(2*s),'ok',...
        'MarkerFaceColor',[0.7 0.7 0.7],...
        'MarkerSize',15); hold on;
    plot(s+0.2,D2(2*s),'dk',...
        'MarkerFaceColor','k',...
        'MarkerSize',15); hold on;
    xlim([0 7])
   
    
end

%
%%
for s=1:length(spots)
    % Hist cont vs seas
    f1=figure(1);
    subplot(1,3,1)
    plot(s-0.2,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Forage')
   
    subplot(1,3,2)
    plot(s-0.2,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Historical 1975-2005'}; {'Pelagic'}])
    
    subplot(1,3,3)
    plot(s-0.2,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title('Demersal')
    
    
    % 2021-2050 cont vs seas
    f2=figure(2);
    subplot(1,3,1)
    plot(s-0.1,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F1(2*s),'ok',...
        'MarkerFaceColor','m',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Forage')
    
    subplot(1,3,2)
    plot(s-0.1,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,P1(2*s),'ok',...
        'MarkerFaceColor','c',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Forecast 2021-2050'}; {'Pelagic'}])
    
    subplot(1,3,3)
    plot(s-0.1,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D1(2*s),'ok',...
        'MarkerFaceColor',[0.9 0.9 0.9],...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title('Demersal')
    
    % 2071-2100 cont vs seas
    f3=figure(3);
    subplot(1,3,1)
    plot(s,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,F2(2*s),'dk',...
        'MarkerFaceColor','r',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Forage')
    
    subplot(1,3,2)
    plot(s,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,P2(2*s),'dk',...
        'MarkerFaceColor','b',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Forecast 2071-2100'}; {'Pelagic'}])
    
    subplot(1,3,3)
    plot(s,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,D2(2*s),'dk',...
        'MarkerFaceColor','k',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title('Demersal')
    
    % hist vs. fore cont
    f4=figure(4);
    subplot(1,3,1)
    plot(s-0.2,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Forage')
    
    subplot(1,3,2)
    plot(s-0.2,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Continuous'}; {'Pelagic'}])
    
    subplot(1,3,3)
    plot(s-0.2,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s-0.1,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title('Demersal')
    
    % hist vs. fore seas
    f5=figure(5);
    subplot(1,3,1)
    plot(s,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F1(2*s),'ok',...
        'MarkerFaceColor','m',...
        'MarkerSize',15); hold on;
    plot(s+0.2,F2(2*s),'dk',...
        'MarkerFaceColor','r',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Forage')
    
    subplot(1,3,2)
    plot(s,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,P1(2*s),'ok',...
        'MarkerFaceColor','c',...
        'MarkerSize',15); hold on;
    plot(s+0.1,P2(2*s),'dk',...
        'MarkerFaceColor','b',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Seasonal'}; {'Pelagic'}])
    
    subplot(1,3,3)
    plot(s,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D1(2*s),'ok',...
        'MarkerFaceColor',[0.9 0.9 0.9],...
        'MarkerSize',15); hold on;
    plot(s+0.2,D2(2*s),'dk',...
        'MarkerFaceColor','k',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title('Demersal')
end
print(f1,'-dpng',[fpath sname 'All_oneloc_hist_rec_PV2.png'])
print(f2,'-dpng',[fpath sname 'All_oneloc_fore2021-2050_rec_PV2.png'])
print(f3,'-dpng',[fpath sname 'All_oneloc_fore2071-2100_rec_PV2.png'])
print(f4,'-dpng',[fpath sname 'All_oneloc_fore_const_rec_PV2.png'])
print(f5,'-dpng',[fpath sname 'All_oneloc_fore_seas_rec_PV2.png'])

%%
for s=1:length(spots)
    % Hist cont vs seas
    f21=figure(21);
    subplot(3,1,1)
    plot(s-0.1,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Historical 1975-2005'}; {'Forage'}])
   
    subplot(3,1,2)
    plot(s-0.1,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Pelagic')
    
    subplot(3,1,3)
    plot(s-0.1,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',spots)
    title('Demersal')
    
    
    % 2021-2050 cont vs seas
    f22=figure(22);
    subplot(3,1,1)
    plot(s-0.1,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F1(2*s),'ok',...
        'MarkerFaceColor','m',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Forecast 2021-2050'}; {'Forage'}])
    
    subplot(3,1,2)
    plot(s-0.1,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,P1(2*s),'ok',...
        'MarkerFaceColor','c',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Pelagic')
    
    subplot(3,1,3)
    plot(s-0.1,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D1(2*s),'ok',...
        'MarkerFaceColor',[0.9 0.9 0.9],...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',spots)
    title('Demersal')
    
    % 2071-2100 cont vs seas
    f23=figure(23);
    subplot(3,1,1)
    plot(s-0.1,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,F2(2*s),'dk',...
        'MarkerFaceColor','r',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Forecast 2071-2100'}; {'Forage'}])
    
    subplot(3,1,2)
    plot(s-0.1,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,P2(2*s),'dk',...
        'MarkerFaceColor','b',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Pelagic')
    
    subplot(3,1,3)
    plot(s-0.1,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.1,D2(2*s),'dk',...
        'MarkerFaceColor','k',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',spots)
    title('Demersal')
    
    % hist vs. fore cont
    f24=figure(24);
    subplot(3,1,1)
    plot(s-0.2,F(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,F2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Continuous'}; {'Forage'}])
    
    subplot(3,1,2)
    plot(s-0.2,P(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,P2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Pelagic')
    
    subplot(3,1,3)
    plot(s-0.2,D(2*s -1),'sk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D1(2*s -1),'ok',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s+0.2,D2(2*s -1),'dk',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',spots)
    title('Demersal')
    
    % hist vs. fore seas
    f25=figure(25);
    subplot(3,1,1)
    plot(s-0.2,F(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(3,:),...
        'MarkerSize',15); hold on;
    plot(s,F1(2*s),'ok',...
        'MarkerFaceColor','m',...
        'MarkerSize',15); hold on;
    plot(s+0.2,F2(2*s),'dk',...
        'MarkerFaceColor','r',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    title([{'Seasonal'}; {'Forage'}])
    
    subplot(3,1,2)
    plot(s-0.2,P(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(1,:),...
        'MarkerSize',15); hold on;
    plot(s,P1(2*s),'ok',...
        'MarkerFaceColor','c',...
        'MarkerSize',15); hold on;
    plot(s+0.2,P2(2*s),'dk',...
        'MarkerFaceColor','b',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',[])
    ylabel('Recruitment variability (PV)')
    title('Pelagic')
    
    subplot(3,1,3)
    plot(s-0.2,D(2*s),'^k',...
        'MarkerFaceColor',cmap_ppt(2,:),...
        'MarkerSize',15); hold on;
    plot(s,D1(2*s),'ok',...
        'MarkerFaceColor',[0.9 0.9 0.9],...
        'MarkerSize',15); hold on;
    plot(s+0.2,D2(2*s),'dk',...
        'MarkerFaceColor','k',...
        'MarkerSize',15); hold on;
    xlim([0 7])
    set(gca,'XTick',1:6,'XTickLabel',spots)
    title('Demersal')
end
print(f21,'-dpng',[fpath sname 'All_oneloc_hist_rec_PV3.png'])
print(f22,'-dpng',[fpath sname 'All_oneloc_fore2021-2050_rec_PV3.png'])
print(f23,'-dpng',[fpath sname 'All_oneloc_fore2071-2100_rec_PV3.png'])
print(f24,'-dpng',[fpath sname 'All_oneloc_fore_const_rec_PV3.png'])
print(f25,'-dpng',[fpath sname 'All_oneloc_fore_seas_rec_PV3.png'])
